spring.application.name=FarmaciaApp
# Base de datos en memoria
spring.datasource.url=jdbc:h2:mem:farmaciadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Consola H2 habilitada en /h2-console
spring.h2.console.enabled=true
